CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	first_name TEXT NOT NULL,
	last_name TEXT NOT NULL,
	email TEXT UNIQUE NOT NULL,
	salt TEXT NOT NULL,
	hash TEXT NOT NULL,
	jwt TEXT UNIQUE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE todos(
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users (id),
	name TEXT NOT NULL,
	done BOOLEAN DEFAULT false,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
